-- ============================================================================
-- config/Buildings.lua
-- 产业定义（金币帝国 · 现实商业主题）
-- 购买价格公式: Price(N) = floor(BaseCost × 1.15^N)
-- ============================================================================

local Buildings = {}

--- 20 个产业（按发展阶段排列）
--- 每个产业的 cpsAdd 为【单个】的每秒产出
Buildings.buildings = {
    -- ═══════════ 第一阶段：街头谋生 ═══════════
    {
        id = "cursor",
        name = "临时工",
        icon = "👆",
        iconImage = "image/临时工.png",
        desc = "发传单、跑腿 +0.1/秒",
        baseCost = 15,
        costMul = 1.15,
        count = 0,
        cpsAdd = 0.1,
    },
    {
        id = "grandma",
        name = "小作坊",
        icon = "👵",
        iconImage = "image/小作坊.png",
        desc = "手工作坊代加工 +1/秒",
        baseCost = 100,
        costMul = 1.15,
        count = 0,
        cpsAdd = 1,
    },
    {
        id = "farm",
        name = "种植园",
        icon = "🌾",
        iconImage = "image/种植园.png",
        desc = "经济作物种植 +8/秒",
        baseCost = 1100,
        costMul = 1.15,
        count = 0,
        cpsAdd = 8,
    },
    {
        id = "mine",
        name = "采矿场",
        icon = "⛏️",
        iconImage = "image/采矿场.png",
        desc = "矿产资源开发 +47/秒",
        baseCost = 12000,
        costMul = 1.15,
        count = 0,
        cpsAdd = 47,
    },
    -- ═══════════ 第二阶段：工业起步 ═══════════
    {
        id = "factory",
        name = "制造工厂",
        icon = "🏭",
        iconImage = "image/制造工厂.png",
        desc = "流水线标准化生产 +260/秒",
        baseCost = 130000,
        costMul = 1.15,
        count = 0,
        cpsAdd = 260,
    },
    {
        id = "bank",
        name = "商业银行",
        icon = "🏦",
        iconImage = "image/商业银行.png",
        desc = "存贷利差钱生钱 +1,400/秒",
        baseCost = 1400000,
        costMul = 1.15,
        count = 0,
        cpsAdd = 1400,
    },
    {
        id = "temple",
        name = "商业地产",
        icon = "⛩️",
        iconImage = "image/商业地产.png",
        desc = "写字楼商场收租 +7,800/秒",
        baseCost = 20000000,
        costMul = 1.15,
        count = 0,
        cpsAdd = 7800,
    },
    {
        id = "wizard",
        name = "研发中心",
        icon = "🧙",
        iconImage = "image/研发中心.png",
        desc = "专利技术授权 +44K/秒",
        baseCost = 330000000,
        costMul = 1.15,
        count = 0,
        cpsAdd = 44000,
    },
    -- ═══════════ 第三阶段：商业帝国 ═══════════
    {
        id = "shipment",
        name = "国际物流",
        icon = "🐫",
        iconImage = "image/国际物流.png",
        desc = "全球物流网络 +260K/秒",
        baseCost = 5.1e9,
        costMul = 1.15,
        count = 0,
        cpsAdd = 260000,
    },
    {
        id = "alchemy",
        name = "能源集团",
        icon = "⚗️",
        iconImage = "image/能源集团.png",
        desc = "石油新能源全产业链 +1.6M/秒",
        baseCost = 7.5e10,
        costMul = 1.15,
        count = 0,
        cpsAdd = 1600000,
    },
    {
        id = "portal",
        name = "电商平台",
        icon = "🌀",
        iconImage = "image/电商平台.png",
        desc = "线上交易抽成 +10M/秒",
        baseCost = 1e12,
        costMul = 1.15,
        count = 0,
        cpsAdd = 10000000,
    },
    -- ═══════════ 第四阶段：科技寡头 ═══════════
    {
        id = "timeMachine",
        name = "期货交易所",
        icon = "⏳",
        iconImage = "image/期货交易所.png",
        desc = "期货期权套利 +65M/秒",
        baseCost = 1.4e13,
        costMul = 1.15,
        count = 0,
        cpsAdd = 65000000,
    },
    {
        id = "antimatter",
        name = "核能电站",
        icon = "⚛️",
        iconImage = "image/核能电站.png",
        desc = "核聚变无限能源 +430M/秒",
        baseCost = 1.7e14,
        costMul = 1.15,
        count = 0,
        cpsAdd = 430000000,
    },
    {
        id = "prism",
        name = "太空采矿",
        icon = "🔮",
        iconImage = "image/太空采矿.png",
        desc = "小行星带铂金开采 +2.9B/秒",
        baseCost = 2.1e15,
        costMul = 1.15,
        count = 0,
        cpsAdd = 2900000000,
    },
    -- ═══════════ 第五阶段：宇宙首富 ═══════════
    {
        id = "chancemaker",
        name = "主权基金",
        icon = "🏺",
        iconImage = "image/主权基金.png",
        desc = "投资整个国家和行业 +21B/秒",
        baseCost = 2.6e16,
        costMul = 1.15,
        count = 0,
        cpsAdd = 21000000000,
    },
    {
        id = "fractal",
        name = "量化交易",
        icon = "🔷",
        iconImage = "image/量化交易.png",
        desc = "AI高频交易毫秒套利 +150B/秒",
        baseCost = 3.1e17,
        costMul = 1.15,
        count = 0,
        cpsAdd = 150000000000,
    },
    {
        id = "console",
        name = "数字货币",
        icon = "💻",
        iconImage = "image/数字货币.png",
        desc = "发行全球数字货币 +1.1T/秒",
        baseCost = 7.1e19,
        costMul = 1.15,
        count = 0,
        cpsAdd = 1.1e12,
    },
    {
        id = "idleverse",
        name = "星际殖民",
        icon = "🌌",
        iconImage = "image/星际殖民.png",
        desc = "火星殖民地经济体 +8.3T/秒",
        baseCost = 1.2e22,
        costMul = 1.15,
        count = 0,
        cpsAdd = 8.3e12,
    },
    {
        id = "cortex",
        name = "脑机接口",
        icon = "🧠",
        iconImage = "image/脑机接口.png",
        desc = "意识操控数字经济 +64T/秒",
        baseCost = 1.9e24,
        costMul = 1.15,
        count = 0,
        cpsAdd = 6.4e13,
    },
    {
        id = "you",
        name = "宇宙财团",
        icon = "👑",
        iconImage = "image/宇宙财团.png",
        desc = "横跨太阳系的商业帝国 +510T/秒",
        baseCost = 5.4e26,
        costMul = 1.15,
        count = 0,
        cpsAdd = 5.1e14,
    },
    -- ═══════════ 第六阶段：超维存在 ═══════════
    {
        id = "timeGuild",
        name = "时空商会",
        icon = "🌀",
        iconImage = "image/时空商会_20260507051221.png",
        desc = "跨维度贸易联盟 +4.1Qa/秒",
        baseCost = 1.3e29,
        costMul = 1.15,
        count = 0,
        cpsAdd = 4.1e15,
    },
    {
        id = "darkAlchemy",
        name = "暗物质炼金",
        icon = "🔮",
        iconImage = "image/暗物质炼金_20260507051331.png",
        desc = "暗物质能源转化 +33Qa/秒",
        baseCost = 3.1e31,
        costMul = 1.15,
        count = 0,
        cpsAdd = 3.3e16,
    },
    {
        id = "civSeed",
        name = "文明种子",
        icon = "🌱",
        iconImage = "image/文明种子_20260507051227.png",
        desc = "播种新文明收获文明税 +270Qa/秒",
        baseCost = 7.5e33,
        costMul = 1.15,
        count = 0,
        cpsAdd = 2.7e17,
    },
    {
        id = "causalBank",
        name = "因果银行",
        icon = "♾️",
        iconImage = "image/因果银行_20260507051231.png",
        desc = "操控因果律获取必然财富 +2.2Qi/秒",
        baseCost = 1.8e36,
        costMul = 1.15,
        count = 0,
        cpsAdd = 2.2e18,
    },
    {
        id = "omniscient",
        name = "全知集团",
        icon = "👁️",
        iconImage = "image/全知集团_20260507051230.png",
        desc = "全知全能的终极商业体 +18Qi/秒",
        baseCost = 4.4e38,
        costMul = 1.15,
        count = 0,
        cpsAdd = 1.8e19,
    },
}

-- 初始化每个建筑的累计产出
for _, b in ipairs(Buildings.buildings) do
    b.totalProduced = 0
end

return Buildings
