-- ============================================================================
-- config/Upgrades.lua
-- 点击强化升级数据定义（四条升级线）
-- 金币帝国 · 现实商业主题
-- ============================================================================

local Upgrades = {}

--- 点击强化升级（三条升级线）
--- 分类 category: "mouse" | "finger" | "lucky"
---
--- 鼠标升级线: 每级点击额外获得 +1% 当前 CpS（一次性购买，中期）
--- 手指升级线: 每个非临时工产业为点击增加固定金币（一次性购买，中后期）
--- 幸运升级线: 影响黄金商机出现频率 / Buff 持续时间（一次性购买）
Upgrades.clickUpgrades = {
    -- ========== 鼠标升级线（+1% CpS → 点击，按点击次数解锁） ==========
    {
        id = "mouse_copper",
        name = "铜牌业务员",
        icon = "🥉",
        iconImage = "image/icon_copper_medal_20260415010824.png",
        desc = "点击 +1% 每秒产出",
        baseCost = 50000,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "mouse",
        cpsPercentAdd = 0.01,
        needClicks = 100,
    },
    {
        id = "mouse_silver",
        name = "银牌经理人",
        icon = "🥈",
        iconImage = "image/icon_silver_medal_20260415010843.png",
        desc = "点击 +1% 每秒产出",
        baseCost = 5e6,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "mouse",
        cpsPercentAdd = 0.01,
        needClicks = 500,
    },
    {
        id = "mouse_gold",
        name = "金牌操盘手",
        icon = "🥇",
        iconImage = "image/icon_gold_medal_20260415010833.png",
        desc = "点击 +1% 每秒产出",
        baseCost = 5e8,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "mouse",
        cpsPercentAdd = 0.01,
        needClicks = 1000,
    },
    {
        id = "mouse_platinum",
        name = "铂金投资人",
        icon = "💠",
        iconImage = "image/icon_platinum_gem_20260415010843.png",
        desc = "点击 +1% 每秒产出",
        baseCost = 5e10,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "mouse",
        cpsPercentAdd = 0.01,
        needClicks = 5000,
    },
    {
        id = "mouse_diamond",
        name = "钻石基金经理",
        icon = "💎",
        iconImage = "image/icon_diamond_20260415010826.png",
        desc = "点击 +1% 每秒产出",
        baseCost = 5e12,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "mouse",
        cpsPercentAdd = 0.01,
        needClicks = 10000,
    },
    -- ========== 手指升级线（按非临时工产业数加成） ==========
    {
        id = "finger_1k",
        name = "初级人脉",
        icon = "☝️",
        iconImage = "image/icon_finger_one_20260415010830.png",
        desc = "每个非临时工产业 +0.1/点击",
        baseCost = 1e5,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "finger",
        fingerBase = 0.1,
        fingerMul = 1,
        needCursor = 25,
    },
    {
        id = "finger_10k",
        name = "商业人脉",
        icon = "✌️",
        iconImage = "image/icon_finger_victory_20260415010827.png",
        desc = "人脉效果 x5",
        baseCost = 1e7,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "finger",
        fingerBase = 0.1,
        fingerMul = 5,
        needCursor = 50,
    },
    {
        id = "finger_100m",
        name = "政商关系",
        icon = "🤞",
        iconImage = "image/icon_finger_cross_20260415010825.png",
        desc = "人脉效果 x10",
        baseCost = 1e9,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "finger",
        fingerBase = 0.1,
        fingerMul = 10,
        needCursor = 100,
    },
    {
        id = "finger_1t",
        name = "全球人脉网",
        icon = "🖐️",
        iconImage = "image/icon_finger_five_20260415010832.png",
        desc = "人脉效果 x20",
        baseCost = 1e11,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "finger",
        fingerBase = 0.1,
        fingerMul = 20,
        needCursor = 150,
    },
    -- ========== 黄金商机升级线（按点击商机次数解锁） ==========
    {
        id = "lucky_day",
        name = "商业嗅觉",
        icon = "🍀",
        iconImage = "image/icon_clover_20260415010829.png",
        desc = "黄金商机出现频率 x2，停留时间 x2",
        baseCost = 777777777,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "lucky",
        luckyFreqMul = 2,
        luckyStayMul = 2,
        needLuckyClicks = 7,
    },
    {
        id = "lucky_serendipity",
        name = "市场直觉",
        icon = "🌟",
        iconImage = "image/icon_star_glow_20260415010925.png",
        desc = "黄金商机出现频率再 x2，停留时间再 x2",
        baseCost = 77777777777,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "lucky",
        luckyFreqMul = 2,
        luckyStayMul = 2,
        needLuckyClicks = 27,
    },
    {
        id = "lucky_getlucky",
        name = "风口预判",
        icon = "✨",
        iconImage = "image/icon_sparkles_20260415010932.png",
        desc = "黄金商机效果持续时间 x2",
        baseCost = 77777777777777,
        costMul = 1,
        maxCount = 1,
        count = 0,
        category = "lucky",
        luckyDurMul = 2,
        needLuckyClicks = 77,
    },
}

return Upgrades
